Surface the LastErrorValue in json output
mozilla-services/minidump-stackwalk pull request #17
Opened 2021-03-18 15:04 UTC by Gankra

I thiiiink this should work but I still need to figure out how to load these changes into the docker image for testing

2021-03-18 15:05 UTC, willkg commented
You can build a new Docker image with `make build`. Does that help at all?

2021-03-18 15:37 UTC, Gankra commented
huh, I am completely baffled at why this hunk is being rejected: 

```
$ cat breakpad/src/src/processor/call_stack.cc.rej
--- src/processor/call_stack.cc
+++ src/processor/call_stack.cc
@@ -44,11 +44,12 @@ CallStack::~CallStack() {

 void CallStack::Clear() {
   for (vector<StackFrame *>::const_iterator iterator = frames_.begin();
        iterator != frames_.end();
        ++iterator) {
     delete *iterator;
   }
   tid_ = 0;
+  last_error_ = 0;
 }

 }  // namespace google_breakpad
```

2021-03-22 08:33 UTC, gabrielesvelto requested changes
Just a couple of changes are needed, the rest is fine.

2021-03-22 08:33 UTC, gabrielesvelto commented on minidump-stackwalk/stackwalker.cc
> +    thread["last_error_value"] = ToHex(raw_stack.last_error());
print this out only if `raw_stack.last_error()` is non-zero

2021-03-22 08:33 UTC, gabrielesvelto commented on breakpad-patches/16-get-last-error.patch
> +   for (vector<StackFrame *>::const_iterator iterator = frames_.begin();
This line reads:
```
   for (vector<StackFrame*>::const_iterator iterator = frames_.begin();
```
In Breakpad sources, I think this is why the patch doesn't apply.

2021-03-22 11:58 UTC, Gankra commented
comments addressed / patch fixed

2021-03-22 21:53 UTC, gabrielesvelto approved these changes

2021-03-22 21:53 UTC, merged